export const bossQuotes = [
  "Let's make this project the best it can be, or at least better than Bob's team's project down the hall.",
  "I know we're behind schedule, but let's not waste any more time talking about it. Just get it done.",
  "I know we're under a lot of pressure to meet this deadline, but remember, the only thing that's impossible is a rhinoceros trying to juggle.",
  "I don't care how you do it, just get it done. If you need to hire a team of monkeys to type the report, go for it.",
  "I know this project is a little outside our comfort zone, but hey, if we succeed, we'll be the talk of the industry!",
  "I know we're facing some tough challenges, but remember, we're like a slinky. We may not be much to look at, but we always find a way to get things done.",
  "I know this project is going to be a lot of hard work, but think of it as a marathon, not a sprint. And remember, the finish line is a cold beer and a warm couch.",
  "I know we're under a tight deadline, but remember, we're like a rubber band. We may stretch and bend, but we always bounce back.",
  "I know this project is going to be a lot of hard work, but remember, we're like a team of superheroes. We may have our ups and downs, but we always come out on top.",
  "I know we're facing some tough challenges, but remember, we're like a pack of wild animals. We may not always be the biggest or strongest, but we always find a way to survive and thrive.",
  "I know this project is going to be a lot of hard work, but remember, we're like a team of pirates. We may not always have a clear map, but we always find a way to make it to our treasure.",
  "I know we're under a lot of pressure to meet this deadline, but remember, we're like a team of ninja warriors. We may face obstacles, but we always find a way to overcome them.",
  "I know we're facing some tough challenges, but remember, we're like a Lego set. We may have a lot of different pieces, but when we work together, we can build anything.",
  "I know this project is going to be a lot of hard work, but remember, we're like a puzzle. We may have a lot of pieces to fit together, but when we do, we create something beautiful.",
  "I'm not arguing, I'm just explaining why I'm right.",
  "I'm not arguing, I'm just trying to come to a mutual understanding.",
  "I'm not arguing, I'm just trying to get to the bottom of this.",
  "I'm not arguing, I'm just trying to understand your perspective.",
  "I have full confidence in your ability to tackle this challenge and come out on top.",
  "I believe in you and your potential to succeed.",
  "I am confident that together, we can achieve anything.",
  "Let's work together to make this our best year yet.",
  "I understand that you may be feeling overwhelmed, but we need to work faster in order to meet our goals.",
  "We need to pick up the pace if we want to meet this deadline.",
  "Let's try to work smarter and faster in order to get this done.",
  "Let's break this project down into smaller tasks and tackle them one at a time.",
  "I'm not saying it's going to be easy, I'm just saying it's going to be worth it.",
  "Let's make like a tree and leaf this project behind!",
  "Time is money, so let's get this done and make some dough!",
  "The early bird gets the worm, so let's get to work!",
  "Let's work together and make this project a piece of cake!",
  "Let's get this done and be the cream of the crop!",
  "Let's work together and make this project a walk in the park!",
  "Let's get this done and be the top of the food chain!",
  "We have the skills and talent to make this project a breeze!",
  "Let's work together and make this project a smooth ride!",
  "Let's get this done and be the cherry on top of a great day!",
];
